cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jiaxuanma.shu@gmail.com:
      email: jiaxuanma.shu@gmail.com
      name: jiaxuanma.shu@gmail.com
      password: $2b$12$XS.lHwBdAbKU3aPoz1C2p.Au6JHZW.fit9MEEvpp.tAGNMYh5qO0e
    mlmd:
      email: mlmd
      name: mlmd
      password: $2b$12$ZvWIVrevprn.9odEKWmojev1YT5H7v5MB89Jq00DJaQzPM/5aA6Bq
preauthorized:
  emails:
  - mjx@shu.edu.com
