cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    e2m:
      email: mjx@shu.edu.cn
      name: e2m
      password: $2b$12$KlJQly07paFsxpGkmA0E1.epXJT3VDS/1SDm5ipOBf/MSugXmC/9G
    mjx@shu.edu.cn:
      email: mjx@shu.edu.cn
      name: mjx@shu.edu.cn
      password: $2b$12$5D2By5uFUmXfJO4XgYD9vOXUQRfKYPuXJ71BXEFswkXId1rnhjC.2
preauthorized:
  emails:
  - mjx@shu.edu.com
